# Generated by Django 4.1 on 2022-08-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProdApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_id',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
